services:
  - type: web
    name: jekle-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.webhook:app
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /opt/render/data
      sizeGB: 10

