services:
  - type: web
    name: messenger-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.webhook:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0